# Site settings
title: Thomas Ying
email: 
description: Thomas Ying's personal website
# baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site

# Identity
your-name: Thomas Ying
your-title: Civil Engineering Student

# Social settings
linkedin_url: https://www.linkedin.com/in/tchying/

# Build settings
markdown: kramdown
remote_theme: tchying/identity-jekyll-theme

plugins:
  - jekyll-seo-tag
